### ISSUE TITLE
Add a thorough test suite

### ISSUE THREAD

**Issue by pjenvey** [loads/ardere#26]
Tools like loads-broker/ardere really need an extensive test suite for sane development/test cycles.

Though tricky/annoying to build, we should be able to verify all the edges: ardere with a certain test plan will produce the following boto3 calls with the following arguments. All without the need to actually hit AWS.

**Comment by bbangert** [comment]
PR #28 will close this.

**Comment by bbangert** [comment]
Closed by  #28.
