### ISSUE TITLE
Add telegraf container per task def

### ISSUE THREAD

**Issue by bbangert** [loads/ardere#33]
To log system metrics and handle statsd reporting to an InfluxDB instance, each task definition should include a telegraf container that is linked.

**Comment by bbangert** [comment]
Depends on #19 so there's somewhere to actually send the metrics.

**Comment by pjenvey** [comment]
Here's a sample telegraf config file, enables statsd and some basic system capturing

**Comment by pjenvey** [comment]
https://pastebin.mozilla.org/8982907
